version: "3.8"

## For Nvidia GPU's - You probably want to uncomment this
x-nvidia-gpu: &nvidia-gpu-config
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]

services:
  setup-{{USER}}:
    extends:
      file: advanced-base.yml
      service: setup-base
    environment:
      GIT_USER: {{USER}}
    volumes:
      - ${USERS_WORKSPACE}/{{USER}}/config:/config:rw

  idea-docker-{{USER}}:
    container_name: idea-docker-{{USER}}
    extends:
      file: advanced-base.yml
      service: idea-docker-base
    depends_on:
      setup-{{USER}}:
        condition: service_healthy
    environment:
      GIT_USER: {{USER}}
    ports:
      - "5800:5800"
      - "5900:5900"
      - "9520:9527"
      - "5173:5173"
      - "2425:2425"
      - "8890:8892"
    volumes:
      - ${USERS_WORKSPACE}/{{USER}}/config:${USER_HOME}:rw
      - ${USERS_WORKSPACE}/{{USER}}/projects:${IDEA_PROJECTS_HOME}:rw
